[package]
name = "warp-devices"
version = "0.1.0"
edition = "2021"

[dependencies]

[dev-dependencies]
criterion = "0.3"
packed_simd_2 = "0.3.5"
rand = { version = "0.8.4", features = ["simd_support"] }

[[bench]]
name = "varium_c1100"
harness = false
