[package]
name = "warp-devices"
version = "0.2.2"
edition = "2021"

[dependencies]
enum-iterator = "0.7"
enum-iterator-derive = "0.7"
log = "0.4"
num_enum = "0.5"

[dev-dependencies]
criterion = "0.3"
env_logger = "0.9"
itertools = "0.10"
packed_simd_2 = "0.3.5"
rand = { version = "0.8.4", features = ["simd_support"] }
test-log = "0.2.8"

[[bench]]
name = "varium_c1100"
harness = false

[[example]]
name = "cms_regs"

[[example]]
name = "card_info"
