[package]
name = "warpshell"
version = "0.1.0"
edition = "2021"

[lib]
name = "warpshell"
path = "src/lib.rs"

[[bin]]
name = "warpshell-cli"
path = "src/warpshell-cli/warpshell-cli.rs"

[dependencies]
anyhow = "1.0"
clap = {version = "4.0.27", features = ["derive"]}
sha2 = "0.10.6"
